from datetime import datetime
from ai_engine.chains.assistant_chain import get_llm
from ai_engine.prompts.templates import HANDOVER_PROMPT

def run_handover_chain(employee_data: dict, simulation_data: dict) -> dict:
    """
    Assembles profile data and simulation risks into HANDOVER_PROMPT,
    queries Gemini, and parses the output into a structured JSON handover object.
    """
    llm = get_llm()
    
    employee_name = employee_data.get("name", "Employee")
    employee_role = employee_data.get("role", "Staff")
    team_name = employee_data.get("team", "Unknown")
    tenure_years = employee_data.get("tenure_years", 0.0)
    owned_projects = employee_data.get("owned_projects_names", "None")
    existing_docs = employee_data.get("authored_docs_names", "None")
    
    simulation_gaps = ", ".join(simulation_data.get("undocumented_areas", []))
    if not simulation_gaps:
        simulation_gaps = "No critical undocumented gaps identified."
        
    ramp_weeks = simulation_data.get("estimated_ramp_weeks", 4)
    
    title = f"Knowledge Transfer Brief — {employee_name}, {employee_role}"
    
    if llm:
        try:
            prompt_val = HANDOVER_PROMPT.format(
                employee_name=employee_name,
                employee_role=employee_role,
                team_name=team_name,
                tenure_years=tenure_years,
                owned_projects=owned_projects,
                existing_docs=existing_docs,
                simulation_gaps=simulation_gaps,
                ramp_weeks=ramp_weeks
            )
            response = llm.invoke(prompt_val)
            text = response.content
            
            # Parse sections from standard delimiters
            sections = []
            raw_parts = text.split("--- SECTION:")
            for p in raw_parts:
                if "---" in p:
                    header, body = p.split("---", 1)
                    sections.append({
                        "heading": header.strip(),
                        "body": body.strip()
                    })
                    
            if len(sections) == 4:
                return {
                    "employee_id": employee_data.get("id"),
                    "title": title,
                    "generated_at": "Generated by AI just now",
                    "sections": sections
                }
        except Exception as e:
            print(f"Warning: Handover generation failed: {e}. Using local fallback.")
            pass
            
    # Pure-Python Fallback (for offline runs)
    # Scope
    scope_body = (
        f"This brief covers the active responsibilities of {employee_name} as a {employee_role} on the {team_name} team. "
        f"During their tenure of {tenure_years} years, they have been the primary owner of these projects: {owned_projects}."
    )
    
    # Existing Docs
    docs_body = (
        f"An audit of our files indicates that {employee_name} has authored the following documents in our knowledge base: "
        f"{existing_docs}. Stale documents should be verified immediately as part of the exit checklist."
    )
    
    # Gaps
    gaps_body = (
        f"The simulation process identified the following undocumented areas of tribal knowledge that would walk out the door: "
        f"{simulation_gaps}. Capturing this context is critical to prevent organizational failure."
    )
    
    # Ramp
    ramp_body = (
        f"To mitigate transition friction, we estimate a successor ramp window of {ramp_weeks} weeks. We recommend "
        f"pairing a successor to shadow {employee_name}'s next 2 active sprint cycles and recording walkthroughs of "
        f"their primary database schemas and pipeline parameters."
    )
    
    return {
        "employee_id": employee_data.get("id"),
        "title": title,
        "generated_at": datetime.utcnow().strftime("%B %d, %Y at %H:%M UTC"),
        "sections": [
            {"heading": "Scope", "body": scope_body},
            {"heading": "Existing documentation", "body": docs_body},
            {"heading": "Open knowledge gaps", "body": gaps_body},
            {"heading": "Suggested successor ramp plan", "body": ramp_body}
        ]
    }
