import {
  Employee,
  Project,
  DocumentRecord,
  Team,
  SimulationResult,
  ChatMessage,
  HandoverDoc,
} from "@/types";

export const teams: Team[] = [
  { id: "t-platform", name: "Platform Infrastructure", memberIds: ["e1", "e4", "e7"] },
  { id: "t-payments", name: "Payments & Billing", memberIds: ["e2", "e6"] },
  { id: "t-data", name: "Data & Analytics", memberIds: ["e3", "e8"] },
  { id: "t-growth", name: "Growth Engineering", memberIds: ["e5", "e9", "e10"] },
];

export const employees: Employee[] = [
  {
    id: "e1",
    name: "Priya Nair",
    role: "Principal Infrastructure Engineer",
    team: "Platform Infrastructure",
    avatarColor: "#F0A93B",
    initials: "PN",
    riskScore: 92,
    riskLevel: "critical",
    tenureYears: 7,
    documentationCoverage: 18,
    ownedProjects: ["p1", "p4"],
    dependents: 11,
    lastActive: "2 hours ago",
  },
  {
    id: "e2",
    name: "Marcus Webb",
    role: "Staff Engineer, Billing Core",
    team: "Payments & Billing",
    avatarColor: "#E15C5C",
    initials: "MW",
    riskScore: 81,
    riskLevel: "high",
    tenureYears: 5,
    documentationCoverage: 34,
    ownedProjects: ["p2"],
    dependents: 7,
    lastActive: "1 day ago",
  },
  {
    id: "e3",
    name: "Sofia Reyes",
    role: "Lead Data Engineer",
    team: "Data & Analytics",
    avatarColor: "#46C2D8",
    initials: "SR",
    riskScore: 58,
    riskLevel: "medium",
    tenureYears: 3,
    documentationCoverage: 61,
    ownedProjects: ["p3"],
    dependents: 4,
    lastActive: "3 hours ago",
  },
  {
    id: "e4",
    name: "Daniel Osei",
    role: "Senior SRE",
    team: "Platform Infrastructure",
    avatarColor: "#8FE4F2",
    initials: "DO",
    riskScore: 47,
    riskLevel: "medium",
    tenureYears: 2,
    documentationCoverage: 55,
    ownedProjects: ["p5"],
    dependents: 3,
    lastActive: "5 hours ago",
  },
  {
    id: "e5",
    name: "Lena Kowalski",
    role: "Growth Tech Lead",
    team: "Growth Engineering",
    avatarColor: "#F0A93B",
    initials: "LK",
    riskScore: 39,
    riskLevel: "low",
    tenureYears: 2,
    documentationCoverage: 72,
    ownedProjects: ["p6"],
    dependents: 2,
    lastActive: "30 minutes ago",
  },
  {
    id: "e6",
    name: "Tobias Hahn",
    role: "Payments Architect",
    team: "Payments & Billing",
    avatarColor: "#FF8A8A",
    initials: "TH",
    riskScore: 87,
    riskLevel: "critical",
    tenureYears: 9,
    documentationCoverage: 22,
    ownedProjects: ["p7"],
    dependents: 9,
    lastActive: "Yesterday",
  },
  {
    id: "e7",
    name: "Imani Carter",
    role: "Platform Security Engineer",
    team: "Platform Infrastructure",
    avatarColor: "#46C2D8",
    initials: "IC",
    riskScore: 64,
    riskLevel: "high",
    tenureYears: 4,
    documentationCoverage: 41,
    ownedProjects: ["p8"],
    dependents: 5,
    lastActive: "4 hours ago",
  },
  {
    id: "e8",
    name: "Yuki Tanaka",
    role: "Analytics Engineer",
    team: "Data & Analytics",
    avatarColor: "#8FE4F2",
    initials: "YT",
    riskScore: 28,
    riskLevel: "low",
    tenureYears: 1,
    documentationCoverage: 80,
    ownedProjects: [],
    dependents: 1,
    lastActive: "1 hour ago",
  },
  {
    id: "e9",
    name: "Omar Farouk",
    role: "Frontend Engineer",
    team: "Growth Engineering",
    avatarColor: "#F0A93B",
    initials: "OF",
    riskScore: 22,
    riskLevel: "low",
    tenureYears: 1,
    documentationCoverage: 86,
    ownedProjects: [],
    dependents: 1,
    lastActive: "20 minutes ago",
  },
  {
    id: "e10",
    name: "Hannah Brooks",
    role: "Growth PM",
    team: "Growth Engineering",
    avatarColor: "#E15C5C",
    initials: "HB",
    riskScore: 35,
    riskLevel: "low",
    tenureYears: 2,
    documentationCoverage: 75,
    ownedProjects: ["p6"],
    dependents: 2,
    lastActive: "2 hours ago",
  },
];

export const projects: Project[] = [
  { id: "p1", name: "Core Deployment Pipeline", status: "at-risk", ownerId: "e1", team: "Platform Infrastructure", contributors: ["e1", "e4"] },
  { id: "p2", name: "Subscription Billing Engine", status: "at-risk", ownerId: "e2", team: "Payments & Billing", contributors: ["e2", "e6"] },
  { id: "p3", name: "Customer Analytics Warehouse", status: "on-track", ownerId: "e3", team: "Data & Analytics", contributors: ["e3", "e8"] },
  { id: "p4", name: "Multi-Region Failover", status: "blocked", ownerId: "e1", team: "Platform Infrastructure", contributors: ["e1", "e7"] },
  { id: "p5", name: "Observability Stack Migration", status: "on-track", ownerId: "e4", team: "Platform Infrastructure", contributors: ["e4"] },
  { id: "p6", name: "Onboarding Funnel Revamp", status: "on-track", ownerId: "e5", team: "Growth Engineering", contributors: ["e5", "e9", "e10"] },
  { id: "p7", name: "Legacy Invoicing Bridge", status: "blocked", ownerId: "e6", team: "Payments & Billing", contributors: ["e6"] },
  { id: "p8", name: "Zero-Trust Access Rollout", status: "at-risk", ownerId: "e7", team: "Platform Infrastructure", contributors: ["e7", "e1"] },
];

export const documents: DocumentRecord[] = [
  { id: "d1", title: "Deploy Pipeline Runbook", type: "Runbook", authorId: "e1", lastUpdated: "14 months ago", staleness: "stale" },
  { id: "d2", title: "Billing Engine Architecture", type: "Architecture", authorId: "e2", lastUpdated: "9 months ago", staleness: "aging" },
  { id: "d3", title: "Warehouse ETL SOP", type: "SOP", authorId: "e3", lastUpdated: "1 month ago", staleness: "fresh" },
  { id: "d4", title: "Failover Drill Postmortem", type: "Postmortem", authorId: "e1", lastUpdated: "11 months ago", staleness: "stale" },
  { id: "d5", title: "Observability Onboarding Guide", type: "Onboarding", authorId: "e4", lastUpdated: "2 months ago", staleness: "fresh" },
  { id: "d6", title: "Growth Funnel Experiment Log", type: "SOP", authorId: "e5", lastUpdated: "3 weeks ago", staleness: "fresh" },
  { id: "d7", title: "Legacy Invoicing Bridge Notes", type: "Architecture", authorId: "e6", lastUpdated: "21 months ago", staleness: "stale" },
  { id: "d8", title: "Zero-Trust Rollout SOP", type: "SOP", authorId: "e7", lastUpdated: "6 months ago", staleness: "aging" },
];

export const simulations: Record<string, SimulationResult> = {
  e1: {
    employeeId: "e1",
    impactedProjects: [
      { projectId: "p1", name: "Core Deployment Pipeline", severity: "critical", reason: "Sole maintainer of the release orchestration scripts" },
      { projectId: "p4", name: "Multi-Region Failover", severity: "critical", reason: "Only engineer who has run a full failover drill" },
      { projectId: "p8", name: "Zero-Trust Access Rollout", severity: "high", reason: "Holds undocumented context on policy exceptions" },
    ],
    impactedTeammates: 6,
    knowledgeGapScore: 88,
    estimatedRampWeeks: 14,
    undocumentedAreas: [
      "Manual rollback sequence for region-level outages",
      "Tribal knowledge of CI runner quirks not in any runbook",
      "Informal escalation path with the cloud provider's TAM",
    ],
  },
  e2: {
    employeeId: "e2",
    impactedProjects: [
      { projectId: "p2", name: "Subscription Billing Engine", severity: "high", reason: "Owns reconciliation logic with no peer reviewer" },
    ],
    impactedTeammates: 3,
    knowledgeGapScore: 64,
    estimatedRampWeeks: 8,
    undocumentedAreas: ["Edge-case proration rules", "Currency rounding overrides for 3 legacy markets"],
  },
  e6: {
    employeeId: "e6",
    impactedProjects: [
      { projectId: "p7", name: "Legacy Invoicing Bridge", severity: "critical", reason: "Last remaining engineer who understands the legacy schema" },
      { projectId: "p2", name: "Subscription Billing Engine", severity: "medium", reason: "Co-architect of dunning workflow" },
    ],
    impactedTeammates: 5,
    knowledgeGapScore: 79,
    estimatedRampWeeks: 11,
    undocumentedAreas: ["Legacy schema migration path", "Vendor-specific tax exemption handling"],
  },
};

export const exampleChat: ChatMessage[] = [
  { id: "c1", role: "user", content: "Who is responsible for the deploy pipeline if Priya is out?" },
  {
    id: "c2",
    role: "assistant",
    content:
      "No backup owner is currently assigned. Priya Nair is the sole maintainer of the Core Deployment Pipeline, and the only runbook covering it was last updated 14 months ago. Daniel Osei has partial context from the Observability migration but has not run a full deploy independently.",
    citedDocs: ["Deploy Pipeline Runbook", "Core Deployment Pipeline — contributor log"],
  },
  { id: "c3", role: "user", content: "Which projects depend on Tobias Hahn?" },
  {
    id: "c4",
    role: "assistant",
    content:
      "Two active projects: the Legacy Invoicing Bridge, where he is the last engineer who understands the original schema, and the Subscription Billing Engine, where he co-designed the dunning workflow with Marcus Webb. Both are flagged at-risk or blocked in the project tracker.",
    citedDocs: ["Legacy Invoicing Bridge Notes", "Billing Engine Architecture"],
  },
];

export const handoverDocs: Record<string, HandoverDoc> = {
  e1: {
    employeeId: "e1",
    title: "Knowledge Transfer Brief — Priya Nair, Core Deployment Pipeline",
    generatedAt: "Generated just now",
    sections: [
      {
        heading: "Scope",
        body: "Covers release orchestration, rollback procedures, and the multi-region failover path currently held informally by Priya Nair.",
      },
      {
        heading: "Critical Procedures",
        body: "Step-by-step rollback sequence for region-level outages, including the manual DNS cutover steps not present in the existing runbook.",
      },
      {
        heading: "Open Dependencies",
        body: "The CI runner configuration has undocumented quirks affecting build cache invalidation; the cloud provider TAM escalation path is informal and untracked.",
      },
      {
        heading: "Suggested Successor Ramp Plan",
        body: "Pair Daniel Osei on the next two deploy cycles, shadow the next failover drill end-to-end, and schedule a recorded walkthrough of the rollback sequence within two weeks.",
      },
    ],
  },
};
